plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
title: andickinson.github.io
description: Technical Consultant, Team Leader, Cyber Security Specialist
url: https://andickinson.github.io
defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      author_profile: true
      is_post: true
      permalink: /blog/:categories/:title/
      layout: single
      read_time: true
      comments: false
      share: false
      show_date: true
      related: false
atom_feed:
  hide: true
author:
  avatar: "/assets/images/profile.jpg"
  bio: "Technical Consultant, Team Leader, Cyber Security Specialist"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/a-dickinson"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/andickinson"
  location: "Melbourne, Australia"
  name: "Andrew Dickinson"
search: true